import type { VarCardManifest } from "./types"
import { toVarCardRecordType } from "./types"

const builtinCards: VarCardManifest[] = [
  {
    id: "current-time",
    namespace: "builtin",
    version: "1.0.0",
    title: "Current Time",
    description: "Displays the current timestamp for record entries.",
    icon: "time-outline",
    tags: ["time", "timestamp", "live"],
    readonly: true,
    baseCardId: null,
    recordType: toVarCardRecordType("builtin", "current-time"),
    demoValue: "2026-03-20T12:00:00.000Z",
    schema: {
      kind: "datetime",
      baseType: "CurrentTime",
      inputKind: "datetime",
      label: "Recorded At",
      placeholder: null,
      defaultValue: null,
      helperText: "Populated from the current clock when used in live mode.",
      unit: null,
      format: "iso",
      rows: null,
      min: null,
      max: null,
      step: null,
      language: null,
      accept: null,
      previewMode: null,
      serviceType: null,
      serviceProfileId: null,
      serviceHost: null,
      servicePort: null,
      serviceUsername: null,
      serviceRemotePath: null,
      options: [],
    },
    layout: { variant: "inline", density: "compact", align: "start" },
    appearance: { accentColor: "#2563eb", icon: "time-outline", badge: "Built-in" },
    behavior: { allowManualInput: false, allowCopy: true, liveValue: true },
  },
  {
    id: "user-name",
    namespace: "builtin",
    version: "1.0.0",
    title: "User Name",
    description: "Captures the operator name as a short text field.",
    icon: "person-outline",
    tags: ["identity", "operator", "text"],
    readonly: true,
    baseCardId: null,
    recordType: toVarCardRecordType("builtin", "user-name"),
    demoValue: "Ava Chen",
    schema: {
      kind: "text",
      baseType: "UserName",
      inputKind: "text",
      label: "Operator",
      placeholder: "Enter name",
      defaultValue: "",
      helperText: "Use for manual operator attribution.",
      unit: null,
      format: null,
      rows: null,
      min: null,
      max: null,
      step: null,
      language: null,
      accept: null,
      previewMode: null,
      serviceType: null,
      serviceProfileId: null,
      serviceHost: null,
      servicePort: null,
      serviceUsername: null,
      serviceRemotePath: null,
      options: [],
    },
    layout: { variant: "inline", density: "comfortable", align: "stretch" },
    appearance: { accentColor: "#0f766e", icon: "person-outline", badge: "Built-in" },
    behavior: { allowManualInput: true, allowCopy: true, liveValue: false },
  },
  {
    id: "markdown-note",
    namespace: "builtin",
    version: "1.0.0",
    title: "Markdown Note",
    description: "Supports richer formatted notes in markdown syntax.",
    icon: "document-text-outline",
    tags: ["markdown", "notes", "rich-text"],
    readonly: true,
    baseCardId: null,
    recordType: toVarCardRecordType("builtin", "markdown-note"),
    demoValue: "## Observation\n\nCells reached 80% confluence.",
    schema: {
      kind: "markdown",
      baseType: "AiralogyMarkdown",
      inputKind: "textarea",
      label: "Observation",
      placeholder: "Write notes in markdown",
      defaultValue: "",
      helperText: "Use markdown formatting for headings, lists, and emphasis.",
      unit: null,
      format: null,
      rows: 6,
      min: null,
      max: null,
      step: null,
      language: null,
      accept: null,
      previewMode: null,
      serviceType: null,
      serviceProfileId: null,
      serviceHost: null,
      servicePort: null,
      serviceUsername: null,
      serviceRemotePath: null,
      options: [],
    },
    layout: { variant: "panel", density: "comfortable", align: "stretch" },
    appearance: { accentColor: "#7c3aed", icon: "document-text-outline", badge: "Built-in" },
    behavior: { allowManualInput: true, allowCopy: true, liveValue: false },
  },
  {
    id: "dna-sequence",
    namespace: "builtin",
    version: "1.0.0",
    title: "DNA Sequence",
    description: "Stores nucleotide sequences with sequence-specific semantics.",
    icon: "flask-outline",
    tags: ["sequence", "dna", "bio"],
    readonly: true,
    baseCardId: null,
    recordType: toVarCardRecordType("builtin", "dna-sequence"),
    demoValue: "ATGCGTACCGTTAA",
    schema: {
      kind: "dna",
      baseType: "DNASequence",
      inputKind: "dna",
      label: "Sequence",
      placeholder: "ATGC...",
      defaultValue: "",
      helperText: "Accepts nucleotide characters for sequence capture.",
      unit: "bp",
      format: null,
      rows: 4,
      min: null,
      max: null,
      step: null,
      language: null,
      accept: null,
      previewMode: null,
      serviceType: null,
      serviceProfileId: null,
      serviceHost: null,
      servicePort: null,
      serviceUsername: null,
      serviceRemotePath: null,
      options: [],
    },
    layout: { variant: "panel", density: "comfortable", align: "stretch" },
    appearance: { accentColor: "#dc2626", icon: "flask-outline", badge: "Built-in" },
    behavior: { allowManualInput: true, allowCopy: true, liveValue: false },
  },
  {
    id: "code-snippet",
    namespace: "builtin",
    version: "1.0.0",
    title: "Code Snippet",
    description: "Captures code-like content with language metadata.",
    icon: "code-slash-outline",
    tags: ["code", "script", "developer"],
    readonly: true,
    baseCardId: null,
    recordType: toVarCardRecordType("builtin", "code-snippet"),
    demoValue: "print('hello world')",
    schema: {
      kind: "code",
      baseType: "PyStr",
      inputKind: "code",
      label: "Script",
      placeholder: "Write code",
      defaultValue: "",
      helperText: "Use for small scripts or expression snippets.",
      unit: null,
      format: null,
      rows: 8,
      min: null,
      max: null,
      step: null,
      language: "python",
      accept: null,
      previewMode: null,
      serviceType: null,
      serviceProfileId: null,
      serviceHost: null,
      servicePort: null,
      serviceUsername: null,
      serviceRemotePath: null,
      options: [],
    },
    layout: { variant: "panel", density: "comfortable", align: "stretch" },
    appearance: { accentColor: "#ea580c", icon: "code-slash-outline", badge: "Built-in" },
    behavior: { allowManualInput: true, allowCopy: true, liveValue: false },
  },
  {
    id: "media-asset",
    namespace: "builtin",
    version: "1.0.0",
    title: "Media Asset",
    description: "Upload or reference a lab asset, then render it with a matching preview mode.",
    icon: "videocam-outline",
    tags: ["asset", "file", "video", "preview"],
    readonly: true,
    baseCardId: null,
    recordType: toVarCardRecordType("builtin", "media-asset"),
    demoValue: {
      src: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
      name: "demo.mov",
      mimeType: "video/quicktime",
      size: null,
      lastModified: null,
    },
    schema: {
      kind: "asset",
      baseType: "str",
      inputKind: "text",
      label: "Capture Asset",
      placeholder: "Choose a file or provide a URL",
      defaultValue: null,
      helperText: "Use one card type for videos, images, PDFs, and other lab attachments.",
      unit: null,
      format: null,
      rows: null,
      min: null,
      max: null,
      step: null,
      language: null,
      accept: ".mov,.mp4,video/*",
      previewMode: "video",
      serviceType: null,
      serviceProfileId: null,
      serviceHost: null,
      servicePort: null,
      serviceUsername: null,
      serviceRemotePath: null,
      options: [],
    },
    layout: { variant: "panel", density: "comfortable", align: "stretch" },
    appearance: { accentColor: "#0891b2", icon: "videocam-outline", badge: "Built-in" },
    behavior: { allowManualInput: true, allowCopy: true, liveValue: false },
  },
  {
    id: "ssh-service",
    namespace: "builtin",
    version: "1.0.0",
    title: "SSH Service",
    description: "Reference a remote SSH target, test connectivity, and expose the connection state inside the recorder.",
    icon: "server-outline",
    tags: ["service", "ssh", "remote", "connector"],
    readonly: true,
    baseCardId: null,
    recordType: toVarCardRecordType("builtin", "ssh-service"),
    demoValue: {
      serviceType: "ssh",
      profileId: "lab-cluster",
      host: "cluster.example.org",
      username: "ubuntu",
      port: 22,
      remotePath: "/srv/data",
      status: "idle",
      checkedAt: null,
      message: "Ready to test connection",
    },
    schema: {
      kind: "service",
      baseType: "str",
      inputKind: "text",
      label: "Remote Host",
      placeholder: "Select SSH profile",
      defaultValue: null,
      helperText: "Use this for remote compute, file sync, or service health checks backed by SSH.",
      unit: null,
      format: null,
      rows: null,
      min: null,
      max: null,
      step: null,
      language: null,
      accept: null,
      previewMode: null,
      serviceType: "ssh",
      serviceProfileId: "lab-cluster",
      serviceHost: "cluster.example.org",
      servicePort: 22,
      serviceUsername: "ubuntu",
      serviceRemotePath: "/srv/data",
      options: [],
    },
    layout: { variant: "panel", density: "comfortable", align: "stretch" },
    appearance: { accentColor: "#475569", icon: "server-outline", badge: "Built-in" },
    behavior: { allowManualInput: true, allowCopy: true, liveValue: false },
  },
]

export function getBuiltinVarCardManifests(): VarCardManifest[] {
  return builtinCards.map((card) => ({
    ...card,
    tags: [...card.tags],
    schema: {
      ...card.schema,
      options: card.schema.options.map((option) => ({ ...option })),
    },
    layout: { ...card.layout },
    appearance: { ...card.appearance },
    behavior: { ...card.behavior },
  }))
}
